server:
  port: 8081

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:api-gateway/.env[.properties]
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: Auth
              uri: http://localhost:8082
              predicates:
                - Path=/auth/**
            - id: GitHub
              uri: http://localhost:8082
              predicates:
                - Path=/github/**
              filters:
                - AuthFilter

jwt:
  secret-key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  audience: ${JWT_AUDIENCE}
